export {
  AgentGate,
  APPROVAL_STATUSES,
  DEFAULT_REQUEST_TIMEOUT_MS,
  type AgentGateOptions,
  type ApprovalStatus,
  type ApprovalView,
  type ProxyRequest,
  type ProxyResponse,
  type WaitForApprovalOptions,
} from './client.js';
export {
  AccessDeniedError,
  AgentGateSdkError,
  ApprovalNotGrantedError,
  ApprovalRequiredError,
  ApprovalTimeoutError,
  GatewayError,
  InvalidTokenError,
  LimitExceededError,
  MalformedResponseError,
  TimeoutError,
  TransportError,
  type AgentGateRefusalBody,
  type AgentGateSdkErrorInit,
} from './errors.js';
